<?php
declare(strict_types=1);
use App\Controllers\HomeController; use App\Controllers\AuthController; use App\Controllers\AdminController; use App\Controllers\GerantController; use App\Controllers\AbonneController; use App\Controllers\GerantPaiementController; use App\Controllers\PlanningController;
$router->get('/',[HomeController::class,'index']);
$router->get('/login',[AuthController::class,'showLogin']); $router->post('/login',[AuthController::class,'login']); $router->get('/logout',[AuthController::class,'logout']);
$router->get('/admin/dashboard',[AdminController::class,'dashboard']); $router->get('/admin/abonnes',[AbonneController::class,'index']); $router->get('/admin/abonnes/edit',[AbonneController::class,'edit']); $router->post('/admin/abonnes/edit',[AbonneController::class,'update']); $router->post('/admin/abonnes/delete',[AbonneController::class,'delete']); $router->get('/admin/tarifs',[AdminController::class,'tarifs']); $router->post('/admin/tarifs',[AdminController::class,'tarifsSave']); $router->get('/admin/factures',[AdminController::class,'factures']); $router->post('/admin/factures/cancel',[AdminController::class,'cancelInvoice']); $router->get('/admin/audit',[AdminController::class,'audit']); $router->post('/admin/notifications/delete',[AdminController::class,'deleteNotification']); $router->get('/admin/users',[AdminController::class,'users']); $router->post('/admin/users/create',[AdminController::class,'createGerant']); $router->post('/admin/users/update',[AdminController::class,'updateGerant']); $router->post('/admin/users/delete',[AdminController::class,'deleteGerant']);
$router->get('/gerant/dashboard',[GerantController::class,'dashboard']); $router->get('/gerant/abonnements',[GerantController::class,'abonnements']); $router->get('/gerant/abonnes',[AbonneController::class,'gerantIndex']); $router->get('/gerant/abonnes/create',[AbonneController::class,'gerantCreate']); $router->post('/gerant/abonnes/create',[AbonneController::class,'gerantStore']);
$router->get('/gerant/paiements',[GerantPaiementController::class,'index']); $router->get('/gerant/paiements/create',[GerantPaiementController::class,'create']); $router->post('/gerant/paiements/create',[GerantPaiementController::class,'store']); $router->post('/gerant/paiements/reste',[GerantPaiementController::class,'payReste']); $router->post('/gerant/paiements/reste/cancel',[GerantPaiementController::class,'cancelReste']); $router->get('/facture/pdf',[GerantPaiementController::class,'pdf']);
$router->get('/admin/planning',[PlanningController::class,'admin']); $router->post('/admin/planning/create',[PlanningController::class,'create']); $router->post('/admin/planning/update',[PlanningController::class,'update']); $router->post('/admin/planning/cancel',[PlanningController::class,'cancel']); $router->get('/gerant/planning',[PlanningController::class,'gerant']); $router->post('/gerant/planning/participate',[PlanningController::class,'participate']); $router->post('/gerant/planning/participant/cancel',[PlanningController::class,'cancelParticipant']); $router->get('/gerant/planning/participants',[PlanningController::class,'participants']);
