<?php
declare(strict_types=1);
namespace App\Controllers; use Core\Controller; use Core\Auth; use App\Models\App;
final class AbonneController extends Controller {
 private function validate(array $p): array { foreach(['nom','prenom','tel','adresse','sexe','age'] as $k){ if(trim((string)($p[$k]??''))==='') throw new \RuntimeException('Champ obligatoire manquant : '.$k); } if(!preg_match('/^[0-9 +().-]{6,20}$/',(string)$p['tel'])) throw new \RuntimeException('Téléphone invalide'); if((int)$p['age']<5 || (int)$p['age']>100) throw new \RuntimeException('Âge invalide'); return ['nom'=>trim($p['nom']),'prenom'=>trim($p['prenom']),'tel'=>trim($p['tel']),'adresse'=>trim($p['adresse']),'sexe'=>$p['sexe'],'age'=>(int)$p['age'],'statut'=>$p['statut']??'actif']; }
 private function common(string $view,array $d=[]): void { $this->render($view,array_merge(['user'=>Auth::user(),'baseUrl'=>rtrim(BASE_URL,'/'),'csrf'=>$this->csrfToken(),'flash'=>$this->pullFlash()],$d)); }
 public function index(): void { Auth::requireRole('admin'); $q=trim((string)($_GET['q']??'')); $statut=trim((string)($_GET['statut']??'en_cours')); if(!in_array($statut,['en_cours','expire','all'],true)){$statut='en_cours';} $dateFrom=trim((string)($_GET['date_from']??'')); $dateTo=trim((string)($_GET['date_to']??'')); $daysOp=trim((string)($_GET['days_op']??'')); $daysRaw=trim((string)($_GET['days']??'')); $daysValue=$daysRaw!==''?max(0,(int)$daysRaw):null; $rows=App::adminAbonnes($q,$statut,$dateFrom,$dateTo,$daysOp,$daysValue); $this->common('admin/abonnes/index',['title'=>'Abonnés','active'=>'admin_abonnes','rows'=>$rows,'q'=>$q,'statut'=>$statut,'dateFrom'=>$dateFrom,'dateTo'=>$dateTo,'daysOp'=>$daysOp,'daysValue'=>$daysValue]); }
 public function edit(): void { Auth::requireRole('admin'); $row=App::findAbonne((int)$_GET['id']); $this->common('admin/abonnes/form',['title'=>'Modifier abonné','active'=>'admin_abonnes','row'=>$row,'error'=>null]); }
 public function update(): void { Auth::requireRole('admin'); $this->requireCsrf(); try{ $id=(int)$_POST['idabonne']; App::updateAbonne($id,$this->validate($_POST),Auth::user()); if(isset($_POST['jours_restants']) && $_POST['jours_restants']!==''){ App::setAbonneJoursRestants($id,(int)$_POST['jours_restants'],Auth::user()); } $this->flash('success','Abonné modifié.'); $this->redirect('/admin/abonnes'); }catch(\Throwable $e){ $this->common('admin/abonnes/form',['title'=>'Modifier abonné','active'=>'admin_abonnes','row'=>$_POST,'error'=>$e->getMessage()]); } }
 public function delete(): void { Auth::requireRole('admin'); $this->requireCsrf(); App::deactivateAbonne((int)$_POST['idabonne'],Auth::user(),trim((string)($_POST['motif']??''))); $this->flash('warning','Abonné désactivé.'); $this->redirect('/admin/abonnes'); }
 public function gerantIndex(): void { Auth::requireRole('gerant'); $q=trim((string)($_GET['q']??'')); $qJournalier=trim((string)($_GET['q_journalier']??'')); $type=trim((string)($_GET['type']??'')); $statut=trim((string)($_GET['statut']??'en_cours')); if(!in_array($statut,['en_cours','expire'],true)){$statut='en_cours';} $rows=App::abonneSearch($q,$type,'abonnement'); $journalierRows=App::abonneSearch($qJournalier,$type,'journalier'); $filter=function(array $items)use($statut){ return array_values(array_filter($items,fn($r)=>$statut==='expire' ? (int)($r['jours_restants']??0)<=0 : (int)($r['jours_restants']??0)>0)); }; $this->common('gerant/abonnes/index',['title'=>'Abonnés','active'=>'gerant_abonnes','rows'=>$filter($rows),'journalierRows'=>$filter($journalierRows),'q'=>$q,'qJournalier'=>$qJournalier,'typeFiltre'=>$type,'statutFiltre'=>$statut]); }
 public function gerantCreate(): void { Auth::requireRole('gerant'); $this->common('gerant/abonnes/form',['title'=>'Nouvel abonné','active'=>'gerant_abonnes','row'=>null,'error'=>null]); }
 public function gerantStore(): void { Auth::requireRole('gerant'); $this->requireCsrf(); try{ $id=App::createAbonne($this->validate($_POST),Auth::user()); $this->flash('success','Abonné créé. Vous pouvez maintenant enregistrer son abonnement.'); $this->redirect('/gerant/paiements/create?idabonne='.$id); }catch(\Throwable $e){ $this->common('gerant/abonnes/form',['title'=>'Nouvel abonné','active'=>'gerant_abonnes','row'=>$_POST,'error'=>$e->getMessage()]); } }
}
