<?php
declare(strict_types=1);
namespace App\Controllers;
use Core\Controller; use Core\Auth; use App\Models\App; use App\Models\User; use Config\DB;
final class AdminController extends Controller {
 private function view(string $v,array $d=[]): void { $this->render($v,array_merge(['user'=>Auth::user(),'baseUrl'=>rtrim(BASE_URL,'/'),'csrf'=>$this->csrfToken(),'flash'=>$this->pullFlash()],$d)); }
 public function dashboard(): void { Auth::requireRole('admin'); $filters=['day'=>trim((string)($_GET['day']??'')),'month'=>trim((string)($_GET['month']??'')),'year'=>trim((string)($_GET['year']??''))]; $abonneFilters=['q'=>trim((string)($_GET['q']??'')),'statut'=>trim((string)($_GET['statut']??'en_cours')),'days_op'=>trim((string)($_GET['days_op']??'')),'days_value'=>($_GET['days_value']??'')!==''?(int)$_GET['days_value']:null]; $this->view('admin/dashboard',['title'=>'Dashboard Admin','active'=>'admin_dashboard','stats'=>App::adminDashboard($filters),'abonneFilters'=>$abonneFilters,'adminAbonnes'=>App::adminAbonnes($abonneFilters['q'],$abonneFilters['statut'],'','',$abonneFilters['days_op'],$abonneFilters['days_value'])]); }
 public function tarifs(): void { Auth::requireRole('admin'); $this->view('admin/tarifs',['title'=>'Tarifs','active'=>'admin_tarifs','refs'=>App::refs()]); }
 public function tarifsSave(): void { Auth::requireRole('admin'); $this->requireCsrf(); App::tarifsUpdate($_POST,Auth::user()); $this->flash('success','Tarifs et descriptions mis à jour.'); $this->redirect('/admin/tarifs'); }
 public function factures(): void { Auth::requireRole('admin'); $q=trim((string)($_GET['q']??'')); $dateFrom=trim((string)($_GET['date_from']??'')); $dateTo=trim((string)($_GET['date_to']??'')); $sort=trim((string)($_GET['sort']??'date_facture')); $dir=trim((string)($_GET['dir']??'desc')); $this->view('admin/factures',['title'=>'Factures','active'=>'admin_factures','rows'=>App::factures($q,$dateFrom,$dateTo,$sort,$dir),'q'=>$q,'dateFrom'=>$dateFrom,'dateTo'=>$dateTo,'sort'=>$sort,'dir'=>$dir]); }
 public function cancelInvoice(): void { Auth::requireRole('admin'); $this->requireCsrf(); App::cancelInvoice((int)$_POST['idfacture'],Auth::user(),trim((string)$_POST['motif'])); $this->flash('warning','Facture annulée avec motif.'); $this->redirect('/admin/factures'); }
 public function audit(): void { Auth::requireRole('admin'); $p=DB::pdo(); $filters=['date_from'=>trim((string)($_GET['date_from']??'')),'date_to'=>trim((string)($_GET['date_to']??'')),'action'=>trim((string)($_GET['action']??'')),'user_id'=>(int)($_GET['user_id']??0)]; $where=[]; $params=[]; if($filters['date_from']!==''){ $where[]='DATE(l.created_at)>=?'; $params[]=$filters['date_from']; } if($filters['date_to']!==''){ $where[]='DATE(l.created_at)<=?'; $params[]=$filters['date_to']; } if($filters['action']!==''){ $where[]='l.action LIKE ?'; $params[]='%'.$filters['action'].'%'; } if($filters['user_id']>0){ $where[]='l.user_id=?'; $params[]=$filters['user_id']; } $sql='SELECT l.*,u.username FROM audit_logs l LEFT JOIN users u ON u.iduser=l.user_id'; if($where){ $sql.=' WHERE '.implode(' AND ',$where); } $sql.=' ORDER BY l.idlog DESC LIMIT 500'; $st=$p->prepare($sql); $st->execute($params); $users=$p->query('SELECT iduser,username,role FROM users ORDER BY username')->fetchAll(); $this->view('admin/audit',['title'=>'Historique','active'=>'admin_audit','rows'=>$st->fetchAll(),'filters'=>$filters,'users'=>$users]); }
 public function deleteNotification(): void { Auth::requireRole('admin'); $this->requireCsrf(); App::deleteNotification((int)($_POST['idnotification']??0),Auth::user()); $this->flash('success','Notification supprimée.'); $this->redirect('/admin/dashboard'); }
 public function users(): void { Auth::requireRole('admin'); $this->view('admin/users',['title'=>'Gérants','active'=>'admin_users','rows'=>User::all()]); }
 public function createGerant(): void { Auth::requireRole('admin'); $this->requireCsrf(); User::createGerant($_POST,Auth::user()); $this->flash('success','Compte gérant créé.'); $this->redirect('/admin/users'); }
 public function updateGerant(): void { Auth::requireRole('admin'); $this->requireCsrf(); User::updateGerant((int)$_POST['iduser'],$_POST,Auth::user()); $this->flash('success','Compte gérant modifié.'); $this->redirect('/admin/users'); }
 public function deleteGerant(): void { Auth::requireRole('admin'); $this->requireCsrf(); User::deleteGerant((int)$_POST['iduser'],Auth::user()); $this->flash('warning','Compte gérant désactivé.'); $this->redirect('/admin/users'); }
}

