<?php $content=function()use($rows,$q,$baseUrl,$csrf,$statut,$dateFrom,$dateTo,$daysOp,$daysValue){ ?>
<form class="card border-0 shadow-sm p-3 mb-3 gf-search-form" method="get" action="<?=$baseUrl?>/admin/abonnes">
 <div class="row g-2 align-items-end">
  <div class="col-md-3"><label class="small fw-bold">Recherche</label><input class="form-control gf-live-search" name="q" value="<?=htmlspecialchars($q)?>" placeholder="Nom, téléphone, facture"></div>
  <div class="col-md-2"><label class="small fw-bold">Statut</label><select class="form-select" name="statut"><option value="en_cours" <?=$statut==='en_cours'?'selected':''?>>En cours</option><option value="expire" <?=$statut==='expire'?'selected':''?>>Expirés</option><option value="all" <?=$statut==='all'?'selected':''?>>Tous</option></select></div>
  <div class="col-md-2"><label class="small fw-bold">Créé du</label><input type="date" class="form-control" name="date_from" value="<?=htmlspecialchars($dateFrom)?>"></div>
  <div class="col-md-2"><label class="small fw-bold">Au</label><input type="date" class="form-control" name="date_to" value="<?=htmlspecialchars($dateTo)?>"></div>
  <div class="col-md-1"><label class="small fw-bold">Jours</label><select class="form-select" name="days_op"><option value="">Tous</option><?php foreach(['<','<=','>','>=','='] as $op): ?><option value="<?=$op?>" <?=$daysOp===$op?'selected':''?>><?=$op?></option><?php endforeach; ?></select></div>
  <div class="col-md-1"><label class="small fw-bold">Valeur</label><input type="number" min="0" class="form-control" name="days" value="<?=htmlspecialchars((string)($daysValue??''))?>"></div>
  <div class="col-md-1"><button class="btn btn-dark w-100"><i class="bi bi-search"></i></button></div>
 </div>
</form>
<div class="card p-3 border-0 shadow-sm"><div class="table-responsive"><table class="table table-striped table-hover align-middle gf-zebra-table gf-searchable-table"><thead><tr><th>N°</th><th>Nom</th><th>Téléphone</th><th>Statut</th><th>Fin</th><th>Message</th><th class="gf-action-header">Action</th></tr></thead><tbody><?php foreach($rows as $r): $j=max(0,(int)($r['jours_restants']??0)); $cls=$j<=0?'gf-days-expired':($j<=2?'gf-days-critical':($j<=5?'gf-days-danger':($j<=10?'gf-days-warning':($j<=20?'gf-days-light-success':'gf-days-success')))); ?><tr class="gf-action-row"><td><?=htmlspecialchars($r['numero_abonne']??$r['idabonne'])?></td><td><?=htmlspecialchars($r['nom'].' '.$r['prenom'])?></td><td><?=htmlspecialchars($r['tel'])?></td><td><span class="gf-days-pill <?=$cls?>"><?=$j>0?'En cours':'Expiré'?></span></td><td><?=htmlspecialchars($r['date_fin']??'-')?></td><td><span class="gf-message-pill <?=$cls?>"><?=$j>0?'Fin dans '.$j.' jour(s)':'Expiré'?></span></td><td class="gf-action-cell"><div class="gf-row-actions"><a class="btn btn-sm btn-outline-primary" href="<?=$baseUrl?>/admin/abonnes/edit?id=<?=$r['idabonne']?>">Modifier</a><form method="post" action="<?=$baseUrl?>/admin/abonnes/delete" class="d-inline"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="idabonne" value="<?=$r['idabonne']?>"><input type="hidden" name="motif" value="Désactivation admin"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Désactiver ?')">Supprimer</button></form></div></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="text-center text-muted py-4">Aucun abonné trouvé.</td></tr><?php endif; ?></tbody></table></div></div><?php }; require __DIR__.'/../../layouts/app.php'; ?>
